//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentation.SHARD
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AlliedClans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_AlliedClans()
        {
            this.C_Guild8 = new HashSet<C_Guild>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Ally1 { get; set; }
        public Nullable<int> Ally2 { get; set; }
        public Nullable<int> Ally3 { get; set; }
        public Nullable<int> Ally4 { get; set; }
        public Nullable<int> Ally5 { get; set; }
        public Nullable<int> Ally6 { get; set; }
        public Nullable<int> Ally7 { get; set; }
        public Nullable<int> Ally8 { get; set; }
        public System.DateTime FoundationDate { get; set; }
        public int LastCrestRev { get; set; }
        public int CurCrestRev { get; set; }
    
        public virtual C_Guild C_Guild { get; set; }
        public virtual C_Guild C_Guild1 { get; set; }
        public virtual C_Guild C_Guild2 { get; set; }
        public virtual C_Guild C_Guild3 { get; set; }
        public virtual C_Guild C_Guild4 { get; set; }
        public virtual C_Guild C_Guild5 { get; set; }
        public virtual C_Guild C_Guild6 { get; set; }
        public virtual C_Guild C_Guild7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Guild> C_Guild8 { get; set; }
    }
}
